name: geocoding_android
description: A Flutter Geocoding plugin which provides easy geocoding and reverse-geocoding features.
version: 5.0.0
repository: https://github.com/baseflow/flutter-geocoding/tree/main/geocoding_android
issue_tracker: https://github.com/Baseflow/flutter-geocoding/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  geocoding_platform_interface: ^5.0.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.0.0
  pigeon: ^26.1.2
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    implements: geocoding
    platforms:
      android:
        package: com.baseflow.geocoding
        pluginClass: GeocodingPlugin
        dartPluginClass: GeocodingAndroidFactory
