name: geocoding_platform_interface
description: A common platform interface for the geocoding plugin.
homepage: https://github.com/baseflow/flutter-geocoding/tree/main/geocoding_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 3.1.0

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mockito: ^5.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.10.0"
