name: geocoding_darwin_example
description: "Demonstrates how to use the geocoding_darwin plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1

dependencies:
  baseflow_plugin_template: ^2.2.1
  flutter:
    sdk: flutter

  geocoding_darwin:
    path: ../
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
